_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.22
        t:
            "1":
                - 1
                - 41
                - 49
                - 50
                - 51
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 51
                - 53
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.22
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
adapter_detr:
    value:
        _target_: models.adapterDETR.AdapterDetr
        adapter:
            _target_: models.adapter.Adapter
            input_dim: 512
            output_dim: 256
            seq_len: 1
        train_prediction_heads: true
data:
    value:
        batch_size: 32
        dataset_name: JierunChen/Ref-L4
        feature_path: ./data/longclip-emb
        shuffle: true
        split: val
device:
    value: cuda
num_classes:
    value: 365
optimizer:
    value:
        _target_: torch.optim.AdamW
        lr: 0.001
train:
    value:
        batch_size: 32
        checkpoint_dir: ./checkpoints/rq1-image-only
        epochs: 5
        resume_checkpoint_dir: ${train.checkpoint_dir}/checkpoint_last.pth
        save_interval: 100
wandb:
    value:
        entity: visiblyintelligent
        name: debug
        project: RQ1
